# Generated by Django 4.0.2 on 2024-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
