# Generated by Django 4.0.2 on 2024-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_product_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
