# Generated by Django 4.0.2 on 2024-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_alter_product_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
