# Generated by Django 4.0.2 on 2024-03-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0004_product_sector_product_topic_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_of_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
