# Generated by Django 4.0.2 on 2024-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0007_product_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
