# Generated by Django 4.0.2 on 2024-03-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0008_product_intensity_product_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='insight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
