# Generated by Django 4.0.2 on 2024-03-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0010_product_added_product_country_product_likelihood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_of_products',
        ),
    ]
