# Generated by Django 4.0.2 on 2024-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0011_signup_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='insight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
