# Generated by Django 4.0.2 on 2024-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0014_alter_product_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
